/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.practicaldime.common.avro;
@org.apache.avro.specific.AvroGenerated
public enum AccStatusAvro implements org.apache.avro.generic.GenericEnumSymbol<AccStatusAvro> {
  active, pending, inactive, hidden  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AccStatusAvro\",\"namespace\":\"com.practicaldime.common.avro\",\"symbols\":[\"active\",\"pending\",\"inactive\",\"hidden\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
